# TiDB Cloud Connection
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=3GUjghmRmnCpb1V.root
spring.datasource.password=El8klkKuSBgAxsF3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Environment Variables Configuration
gemini.api.key=${GEMINI_API_KEY}
server.port=${PORT:8080}
